import { describe, expect, it } from 'vitest';
import { IslandMachine } from '@/pill/island';
import { emptyContext } from '@/pill/contracts';
describe('Island state machine', () => {
  it('flows through the real dictation layers and holds width', () => { const m = new IslandMachine(); m.start(0); expect(m.layers).toEqual(['row']); expect(m.width).toBe(236); m.stream({type:'partial',session_id:1,revision:1,committed:'hello ',tentative:'world'}); expect(m.layers).toEqual(['words','row']); expect(m.width).toBe(300); m.work('transcribing',2100); expect(m.layers).toEqual(['work']); expect(m.width).toBe(236); expect(m.frozenSeconds).toBe(2); m.work('polishing',4000); expect(m.width).toBe(236); expect(m.frozenSeconds).toBe(2); m.outcome({outcome:'pasted',words:2}); expect(m.layers).toEqual(['done']); m.rest(); expect(m.layers).toEqual([]); });
  it.each([true,false])('honours backend start-card decision %s', show_start_card => { const m = new IslandMachine(); m.contextEvent({...emptyContext(),generation:1,show_start_card}); m.start(0); expect(m.layers).toEqual(show_start_card ? ['start'] : ['row']); m.foldStart(); expect(m.layers).toEqual(['row']); });
  it('accepts context that resolves after start but not after stop', () => { const m = new IslandMachine(); m.start(0); m.contextEvent({...emptyContext(),generation:1,show_start_card:true}); expect(m.state).toBe('start'); m.work('transcribing',1000); m.contextEvent({...emptyContext(),generation:2,show_start_card:true}); expect(m.state).toBe('transcribing'); });
  it('ignores stale and duplicate context generations', () => { const m = new IslandMachine(); const c = {...emptyContext(),generation:7}; expect(m.contextEvent(c)).toBe(true); expect(m.contextEvent({...c,generation:6,show_start_card:true})).toBe(false); expect(m.contextEvent({...c,show_start_card:true})).toBe(false); expect(m.context.show_start_card).toBe(false); });
  it('does not reuse the previous take start-card decision', () => { const m = new IslandMachine(); m.contextEvent({...emptyContext(),generation:1,show_start_card:true}); m.start(0); m.work('transcribing',1000); m.rest(); m.start(2000); expect(m.state).toBe('listening'); });
  it('does not restart elapsed time for duplicate started events', () => { const m = new IslandMachine(); m.start(0); expect(m.start(1000)).toBe(false); expect(m.startedAt).toBe(0); });
  it('keeps live words above the inline hint', () => { const m = new IslandMachine(); m.start(0); m.stream({type:'partial',session_id:1,revision:1,committed:'hello',tentative:''}); m.hint = true; expect(m.layers).toEqual(['words','hint']); });
  it('ignores old stream starts, sessions, and revisions', () => { const m = new IslandMachine(); m.start(0); m.stream({type:'started',session_id:2,revision:0,engine:'test'}); expect(m.stream({type:'started',session_id:1,revision:0,engine:'test'})).toBe(false); expect(m.stream({type:'partial',session_id:2,revision:1,committed:'one',tentative:''})).toBe(true); expect(m.stream({type:'partial',session_id:2,revision:1,committed:'duplicate',tentative:''})).toBe(false); });
  it('cannot overwrite a running take with an uncorrelated paste outcome', () => { const m = new IslandMachine(); m.start(0); expect(m.outcome({outcome:'pasted',words:2})).toBe(false); expect(m.state).toBe('listening'); });
  it('ignores context and levels older than an observed audio generation', () => { const m = new IslandMachine(); m.start(0); expect(m.observeGeneration(8)).toBe(true); expect(m.contextEvent({...emptyContext(),generation:7})).toBe(false); expect(m.observeGeneration(7)).toBe(false); expect(m.contextEvent({...emptyContext(),generation:8})).toBe(true); });
});
